version: 2
jobs:
  build:
    docker:
      - image: ishiko/gcc-ishiko-cpp-build-prerequisites:0.7.0
    steps:
      - run: 
          name: "Set ISHIKO_CPP_ROOT environment variable and create workspace directory"
          command: mkdir -p /workspace/projects/ishiko/cpp && echo 'export ISHIKO_CPP_ROOT="/workspace/projects/ishiko/cpp"' >> $BASH_ENV
      - checkout:
          path: /workspace/projects/ishiko/cpp/math
      - run:
          name: Build
          command: cd /workspace/projects/ishiko/cpp/math/numbers/build-files/gnumake && make
      - run:
          name: "Install test dependency: Ishiko/C++ BasePlatform"
          command: cd /workspace/projects/ishiko/cpp && git clone https://github.com/ishiko-cpp/base-platform.git && cd base-platform/build-files/gnumake && make
      - run:
          name: "Install test dependency: Ishiko/C++ Errors"
          command: cd /workspace/projects/ishiko/cpp && git clone https://github.com/ishiko-cpp/errors.git && cd errors/build-files/gnumake && make
      - run:
          name: "Install test dependency: Ishiko/C++ FileSystem"
          command: cd /workspace/projects/ishiko/cpp && git clone https://github.com/ishiko-cpp/filesystem.git && cd filesystem/build-files/gnumake && make
      - run:
          name: "Install test dependency: Ishiko/C++ XML"
          command: cd /workspace/projects/ishiko/cpp && git clone https://github.com/ishiko-cpp/xml.git && cd xml/build-files/gnumake && make
      - run:
          name: "Install test dependency: Ishiko/C++ TestFramework/Core"
          command: cd /workspace/projects/ishiko/cpp && git clone https://github.com/ishiko-cpp/test-framework.git && cd test-framework/core/build-files/gnumake && make
      - run:
          name: Test build
          command: cd /workspace/projects/ishiko/cpp/math/numbers/tests/build-files/gnumake && make
      - run:
          name: Run the tests
          command: cd /workspace/projects/ishiko/cpp/math/numbers/tests/build-files/gnumake && ./IshikoNumbersTests --persistent-storage=/build/test-output --junit-xml-test-report=/build/test-results/IshikoNumbers.xml
      - store_artifacts:
          name: Upload test output files
          path: /build/test-output
          destination: test-output
      - store_artifacts:
          name: Upload test report files
          path: /build/test-results/IshikoNumbers.xml
          destination: IshikoNumbers-test-results.xml
      - store_test_results:
          name: Upload test results to CircleCI
          path: /build/test-results/IshikoNumbers.xml
workflows:
  version: 2
  continuous_build:
    jobs:
      - build
  weekly_build:
    jobs:
      - build
    triggers:
      - schedule:
          cron: "0 8 * * 0"
          filters:
            branches:
              only:
                 - main
